---
- name: Ensure each inventory directory exists
  file:
    path: '{{ playbook_dir }}/inventory/{{ item }}'
    state: directory
  with_items: [local, development, staging, production]

- template:
    src: inventory-roles.j2
    dest: '{{ playbook_dir }}/inventory/roles'

- name: Softlink the roles file into each inventory directory
  file:
    src: '../roles'
    dest: '{{ playbook_dir }}/inventory/{{ item }}/roles'
    state: link
  with_items: [local, development, staging, production]

- name: Softlink the ec2.py file into each inventory directory
  file:
    src: '../ec2.py'
    dest: '{{ playbook_dir }}/inventory/{{ item }}/ec2.py'
    state: link
  with_items: [development, staging, production]

- name: Template an ec2.ini for each role
  template:
    src: ec2.ini.j2
    dest: '{{ playbook_dir }}/inventory/{{ item }}/ec2.ini'
  with_items: [development, staging, production]

- name: One time template each inventory hosts file
  template:
    src: inventory-hosts.j2
    dest: '{{ playbook_dir }}/inventory/{{ item }}/hosts'
    force: no
  with_items: [development, staging, production]


#####
- name: Check for existence of ~/prepd
  stat:
    path: '{{ ansible_env.HOME }}/prepd'
  register: prepd

- set_fact:
    credentials_dir: '{{ ansible_env.HOME }}/prepd/credentials/{{ project_name }}'
    data_dir: '{{ ansible_env.HOME }}/prepd/data/{{ project_name }}'
  when: prepd.stat.isdir
  # when: prepd.stat.isdir is defined and prepd.stat.isdir

- set_fact:
    credentials_dir: '{{ project_dir }}/credentials'
    data_dir: '{{ project_dir }}/data'
  when: not prepd.stat.isdir

- name: Ensure each inventory directory exists
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ credentials_dir }}'
    - '{{ data_dir }}'

- name: Create links to external directories for credentials and data
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - { src: '{{ credentials_dir }}', dest: '{{ project_dir }}/credentials' }
    - { src: '{{ data_dir }}', dest: '{{ project_dir }}/data' }
  when: prepd.stat.isdir
