# dev-server/tasks/config
---
- include_role:
    name: prepd/common
  vars:
    machine_env: '{{ config.machine }}'

- include_role:
    name: prepd/yadr
  when: "'yadr' in machine_tools"

- include_role:
    name: prepd/tmuxinator
    tasks_from: config
  when: "'tmuxinator' in machine_tools"

- include_role:
    name: prepd/awscli
  when: "'awscli' in machine_tools"

- include_role:
    name: prepd/ruby
  with_items: "{{ config.languages | selectattr('name', 'equalto', 'ruby') | map(attribute='version') | list }}"
  loop_control:
    loop_var: version
  when: "'ruby' in config_languages"
 
- include_role:
    name: prepd/git

# TODO: refactor to use with_items when that is supported
- include_role:
    name: prepd/postgres
  when: "'postgresql' in config_databases"

- include_role:
    name: prepd/mysql
    tasks_from: config
  vars:
    mysql_config: "{{ (config.databases | selectattr('name', 'equalto', 'mysql') | list)[0] }}"
  when: "'mysql' in config_databases"

- include_role:
    name: prepd/redis
  when: "'redis' in config_databases"
