# dev-server/tasks/deploy
---
- include_role:
    name: prepd/mysql
    tasks_from: deploy
  vars:
    mysql_databases: '{{ deploy.databases.mysql }}'
  when: "'mysql' in deploy_databases"

- include_role:
    name: prepd/git
    tasks_from: repos
  vars:
    repos: '{{ deploy.repos.git }}'
#
# - include_role:
#     name: prepd/env
#   vars:
#     apps: '{{ env_apps }}'
# 
# - include_role:
#     name: prepd/postgres-utils
#   vars:
#     action: 'create-databases'
#     postgres_databases: '{{ databases }}'
 
- include_role:
    name: prepd/rails
  vars:
    apps: '{{ deploy.apps.rails }}'
  when: "'rails' in project_apps"

# - include_role:
#     name: prepd/ember
#   vars:
#      apps: '{{ ember_apps }}'

- include_role:
    name: prepd/tmuxinator
    tasks_from: deploy
  vars:
    files: '{{ deploy.tools.tmuxinator }}'
