#!/usr/bin/env ansible-playbook
---
- hosts: provisioner
  vars:
    project:
      parent_dir: '{{ ansible_env.HOME }}'
      name: otterlog
    git:
      user: git@github.com
      account: speartail
      repository: otterlog
  roles:
    - project
