---
- include_role:
    name: prepd/nginx

- apt:
   name: rsync
   state: present

- user:
    name: admin
    groups: www-data
    append: yes
  become: yes

- file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- name: Template sites available
  template:
    src: nginx-site.conf.j2
    dest: '/etc/nginx/sites-available/{{ item }}.conf'
  with_items: '{{ flavors }}'
  become: yes

- name: Enable sites available
  file:
    src: '/etc/nginx/sites-available/{{ item }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ item }}.conf'
    state: link
  with_items: '{{ flavors }}'
  become: yes
  # TOOD: A method to restart nginx which is a handler in the nginx role
  notify: Restart Nginx

- name: Ensure application directory exists
  file:
    path: '{{ root_directory }}/{{ item }}'
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  with_items: '{{ flavors }}'
  become: yes
