---
# config vars
config_databases: "{{ config.databases | map(attribute='name') | list }}"
config_languages: "{{ config.languages | map(attribute='name') | list }}"

machine_tools: "{{ config.machine.tools | map(attribute='name') | list }}"
project_cis: '{{ config.ci.keys() }}'

# deploy vars
project_apps: '{{ deploy.apps.keys() }}'
deploy_databases: '{{ deploy.databases.keys() }}'
# deploy_databases: "{{ deploy.databases | map(attribute='name') | list }}"
