#!/usr/bin/env ansible-playbook
---
### Config plays
- hosts: api-servers
  tags: config
  tasks:
    - include_role:
        name: api-server
        tasks_from: config

- hosts: api-servers:&pro-train
  tags: config
  tasks:
    - include_role:
        name: api-server
        tasks_from: seed-files
      vars:
        application_flavor: processor
      tags: config-processor
    - include_role:
        name: api-server
        tasks_from: seed-files
      vars:
        application_flavor: training
      tags: config-training

- hosts: api-servers:&sales
  tags: config
  tasks:
    - include_role:
        name: api-server
        tasks_from: seed-files
      vars:
        application_flavor: sales
      tags: config-sales


### Deploy plays
# - hosts: api-servers
#   tags: deploy, deploy-training, deploy-processor, deploy-sales
#   vars_files: ['{{ credentials_file }}']
#   tasks:
#     - include_role:
#         name: api-server
#         tasks_from: image-pull


- hosts: api-servers:&pro-train
  tags: deploy
  tasks:
    - include_role:
        name: api-server
        tasks_from: deploy
      vars:
        application_flavor: processor
        host_port: 13000
      tags: deploy-processor
    - include_role:
        name: api-server
        tasks_from: deploy
      vars:
        application_flavor: training
        host_port: 13001
      tags: deploy-training


- hosts: api-servers:&sales
  tags: deploy
  tasks:
    - include_role:
        name: api-server
        tasks_from: deploy
      vars:
        application_flavor: sales
        host_port: 3000
      tags: deploy-sales
