#!/usr/bin/env ansible-playbook
---
- hosts: app-servers:&pro-train
  tags: config
  vars:
    - domain: example.com
    - root_directory: /srv/www/web-app
  tasks:
    - include_role:
        name: app-server
        tasks_from: config
      vars:
        flavors: [training, processor]

- hosts: app-servers:&sales
  tags: config
  vars:
    - domain: example.com
    - root_directory: /srv/www/web-app
  tasks:
    - include_role:
        name: app-server
        tasks_from: config
      vars:
        flavors: [sales]


###
# Deploy plays
###
- hosts: provisioner
  tags: deploy
  vars_files: ['{{ credentials_file }}']
  vars:
    # TODO: Get the IP from the hostvars lookup
    - username: admin
    - remote_host: 172.16.0.186
    - proxy_string: admin@bastion-staging.example.com
    - tunnel_port: 16389
    - domain: example.com
    - private_key_file: '{{ credentials_dir }}/keys/id_rsa'
    - root_directory: /srv/www/web-app
  tasks:
    - include_role:
        name: prepd/ssh
        tasks_from: open-tunnel
      tags: deploy, deploy-processor, deploy-training
    - include_role:
        name: app-server
        tasks_from: deploy
      vars:
        application_flavor: processor
        api_server_port: 13000
      tags: deploy-processor
    - include_role:
        name: app-server
        tasks_from: deploy
      vars:
        application_flavor: training
        api_server_port: 13001
      tags: deploy-training
    - include_role:
        name: prepd/ssh
        tasks_from: close-tunnel
      tags: deploy, deploy-processor, deploy-training
