#!/usr/bin/env ansible-playbook
---
- hosts: provisioner
  vars:
    - creds_file: terraform
    - key: terraform_default
  tasks:
    - include_role:
        name: prepd/bastion
      vars:
        # state: running

- hosts: another-host
  tasks:
    - debug:
       msg: 'do some stuff on an internal host'
