#!/usr/bin/env ansible-playbook
# export TF_VAR_ec2_key_pair_public_key_path=/home/vagrant/fanclubs/credentials/keys
---
- hosts: provisioner
  roles:
    - { role: terraplate/package, tags: always, name: 'mfwa' }

- hosts: provisioner
  tags: config
  vars:
    - ns: pro-train
  roles:
    - { role: terraplate-components/aws/vpc-public-only, tags: config-vpc, name: vpc }
    - { role: terraplate-components/aws/bastion-host, tags: config-bastion, name: bastion }
    - { role: terraplate-components/aws/sg-rails, tags: config-sg, name: sg }
