#!/usr/bin/env ansible-playbook
---
- hosts: provisioner
  tasks:
    - apt:
        name: git
        state: present

    # See: https://github.com/ansible/ansible/pull/23104/files
    - name: Apply patches to Ansible 2.3
      shell: 'patch < {{ role_path }}/files/{{ item.file }}'
      args:
        chdir: '/usr/local/lib/python2.7/dist-packages/ansible/{{ item.dir }}'
      with_items:
        - { dir: 'playbook', file: 'role_include.py.patch' }
        - { dir: 'executor', file: 'task_executor.py.patch' }
      become: yes
      ignore_errors: yes

    - name: Clone dependent roles
      command: 'git submodule add {{ item.repo }} {{ item.location }}'
      args:
        chdir: '{{ ops_dir }}'
        creates: '{{ item.location }}'
      with_items:
        - { repo: 'git@github.com:rjayroach/prepd-roles.git', location: 'ansible/community-roles/prepd' }
        - { repo: 'git@github.com:rjayroach/terraplate.git', location: 'ansible/community-roles/terraplate' }
        - { repo: 'git@github.com:rjayroach/terraplate-components.git', location: 'ansible/community-roles/terraplate-components' }
