#!/usr/bin/env ansible-playbook
---
- hosts: provisioner
  roles:
    - { role: terraplate/package, tags: always, name: 'mfwa' }

- hosts: provisioner
  tags: config
  vars:
    - ns: pro-train
  roles:
    - { role: terraplate-components/aws/app-server, tags: config-server, name: server }

- hosts: provisioner
  tags: deploy
  environment:
    TF_VAR_ec2_key_pair_public_key_path: '{{ ssh_dir }}'
  tasks:
    - command: tgp
      args:
        chdir: '{{ tf_instances_dir }}/multi-flavor-web-app/local/pro-train'
