#!/usr/bin/env ansible-playbook
---
# Setup location for data and credentials
- hosts: provisioner
  roles:
    - { role: prepd/setup, tags: always }

- hosts: provisioner
  tasks:
    - include_role:
        name: prepd/setup
        tasks_from: inventory
      tags: inventory

