#!/usr/bin/env ansible-playbook
---
# Create credentials and data directories and setup inventories and roles
- hosts: provisioner
  roles:
    - prepd/setup

- hosts: provisioner
  tags: credentials
  roles:
    - prepd/credentials
